x-environment:
  &COMMON_ENVIRONMENT
  LIBRARY_FOLDERS: "draymed_js draymed_py"
version: 2.1
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9
    environment:
      <<: *COMMON_ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Set up tox tests
          working_directory: ./draymed_py
          command: pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "./draymed_py/poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          working_directory: ./draymed_py
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "./draymed_py/poetry.lock" }}
          paths:
            - .tox
  test-javascript:
    docker:
      - image: circleci/node:11.13.0
    environment:
      <<: *COMMON_ENVIRONMENT
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-deps-{{ checksum "./draymed_js/yarn.lock" }}
            - v1-yarn-deps-
      - run:
          name: Set up yarn tests
          command: yarn install --frozen-lockfile
          working_directory: ./draymed_js
      - save_cache:
          key: v1-yarn-deps-{{ checksum "./draymed_js/yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run yarn tests
          command: yarn test
          working_directory: ./draymed_js
  publish-pypi-python-lib:
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e2:7f:86:24:af:1e:01:13:a8:3d:5e:0f:84:1b:e1:90"
      - checkout
      - run:
          name: Publish package to pypi
          command: poetry publish --build --username __token__ --password $PYPI_API_TOKEN
          working_directory: ./draymed_py
  publish-npm-javascript-lib:
    docker:
      - image: circleci/node:11.13.0
    environment:
      <<: *COMMON_ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
          working_directory: ./draymed_js
      - run:
          name: Build the library
          command: yarn build
          working_directory: ./draymed_js
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > .npmrc
          working_directory: ./draymed_js
      - run:
          name: Publish to npm
          command: npm publish --access public
          working_directory: ./draymed_js
  make-version-tags:
    docker:
      - image: cimg/python:9
    environment:
      <<: *COMMON_ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Install deps
          command: pip install --upgrade toml
          working_directory: ./draymed_py
      - run:
          name: Create git tag
          command: git tag v$(python3 parse_version.py)
          working_directory: ./draymed_py
      - run:
          name: Push git tag
          command: git push --tags
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test-python:
          context: polaris-foundation
      - test-javascript:
          context: polaris-foundation
      - publish-pypi-python-lib:
          context: polaris-foundation
          requires:
            - test-python
            - test-javascript
          filters:
            branches:
              only:
                - main
      - publish-npm-javascript-lib:
          context: polaris-foundation
          requires:
            - test-python
            - test-javascript
          filters:
            branches:
              only:
                - main
      - make-version-tags:
          context: polaris-foundation
          requires:
            - publish-pypi-python-lib
            - publish-npm-javascript-lib
          filters:
            branches:
              only:
                - main
